[package]
name = "vsocket"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
byteorder = { version = "1.4.3" }
nix = { version = "0.26.4" }
